server:
  port: 0

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: test
        port: 27018
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: guest
    password: guest
    host: localhost 
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

resilience4j:
  circuitbreaker:
    instances:
      catalog:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15800
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      movies:
        waitDuration: 1000
        maxAttempts: 3
        retryException:
          - feign.FeignException$InternalServerError

queue:
  serie:
    name: serieQueue
  movie:
    name: movieQueue
